# Generated by Django 4.2.26 on 2026-03-05 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_eggs_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
    ]
